-- Phase 7.2 menu seed (generated from lib/mock-data.ts)
-- Seeds menu categories, products, sizes, addons, addon links, and site settings without runtime integration.

begin;

create temporary table seed_menu_categories (
  legacy_id text not null,
  name_ar text not null,
  slug text not null,
  description_ar text,
  sort_order integer not null
) on commit drop;

insert into seed_menu_categories (legacy_id, name_ar, slug, description_ar, sort_order) values
  ('c1', 'كريب لحوم', 'crepe-meat', 'منيو توسكانيني', 0),
  ('c2', 'كريب فراخ', 'crepe-chicken', 'منيو توسكانيني', 1),
  ('c3', 'كريب متنوع', 'crepe-mixed', 'منيو توسكانيني', 2),
  ('c4', 'كريب توسكانيني', 'crepe-tuscanini', 'منيو توسكانيني', 3),
  ('c5', 'كريب حلو', 'crepe-sweet', 'منيو توسكانيني', 4),
  ('c6', 'بيتزا لحوم', 'pizza-meat', 'منيو توسكانيني', 5),
  ('c7', 'بيتزا فراخ', 'pizza-chicken', 'منيو توسكانيني', 6),
  ('c8', 'بيتزا متنوع', 'pizza-mixed', 'منيو توسكانيني', 7),
  ('c9', 'بيتزا توسكانيني', 'pizza-tuscanini', 'منيو توسكانيني', 8),
  ('c10', 'باستا', 'pasta', 'منيو توسكانيني', 9),
  ('c11', 'ساندوتشات فرنساوي', 'sandwiches-french', 'منيو توسكانيني', 10),
  ('c12', 'ساندوتشات كيزر', 'sandwiches-kaiser', 'منيو توسكانيني', 11),
  ('c13', 'مقبلات', 'appetizers', 'منيو توسكانيني', 12),
  ('c14', 'مشروبات', 'drinks', 'منيو توسكانيني', 13),
  ('c15', 'وافل', 'waffle', 'منيو توسكانيني', 14),
  ('c16', 'إضافات كريب', 'crepe-addons', 'منيو توسكانيني', 15);

insert into public.menu_categories (legacy_id, name_ar, slug, description_ar, sort_order, is_active)
select legacy_id, name_ar, slug, description_ar, sort_order, true
from seed_menu_categories
on conflict (slug) do update set
  legacy_id = excluded.legacy_id,
  name_ar = excluded.name_ar,
  description_ar = excluded.description_ar,
  sort_order = excluded.sort_order,
  is_active = true;

create temporary table seed_products (
  legacy_id text not null,
  category_slug text not null,
  name_ar text not null,
  description_ar text,
  price_from numeric(10,2) not null,
  base_price numeric(10,2),
  availability text not null,
  sort_order integer not null
) on commit drop;

insert into seed_products (legacy_id, category_slug, name_ar, description_ar, price_from, base_price, availability, sort_order) values
  ('cm1', 'crepe-meat', 'برجر', 'كريب لحوم', 40.00, null, 'available', 0),
  ('cm2', 'crepe-meat', 'سوسيس', 'كريب لحوم', 40.00, null, 'available', 1),
  ('cm3', 'crepe-meat', 'ميكس لحوم برجر ع سوسيس', 'كريب لحوم', 60.00, null, 'available', 2),
  ('cm4', 'crepe-meat', 'سجق', 'كريب لحوم', 60.00, null, 'available', 3),
  ('cm5', 'crepe-meat', 'كفتة', 'كريب لحوم', 75.00, null, 'available', 4),
  ('cm6', 'crepe-meat', 'مفروم', 'كريب لحوم', 85.00, null, 'available', 5),
  ('cm7', 'crepe-meat', 'شاورما لحم', 'كريب لحوم', 85.00, null, 'available', 6),
  ('cm8', 'crepe-meat', 'فاهيتا لحم', 'كريب لحوم', 95.00, null, 'available', 7),
  ('cc1', 'crepe-chicken', 'شاورما فراخ', 'كريب فراخ', 50.00, null, 'available', 8),
  ('cc2', 'crepe-chicken', 'فاهيتا فراخ', 'كريب فراخ', 70.00, null, 'available', 9),
  ('cc3', 'crepe-chicken', 'شيش', 'كريب فراخ', 55.00, null, 'available', 10),
  ('cc4', 'crepe-chicken', 'استربس', 'كريب فراخ', 50.00, null, 'available', 11),
  ('cc5', 'crepe-chicken', 'بانيه', 'كريب فراخ', 50.00, null, 'available', 12),
  ('cc6', 'crepe-chicken', 'زينجر', 'كريب فراخ', 55.00, null, 'available', 13),
  ('cc7', 'crepe-chicken', 'برجر ع بانيه', 'كريب فراخ', 95.00, null, 'available', 14),
  ('cx1', 'crepe-mixed', 'بطاطس', 'كريب متنوع', 40.00, null, 'available', 15),
  ('cx2', 'crepe-mixed', 'مشروم', 'كريب متنوع', 70.00, null, 'available', 16),
  ('cx3', 'crepe-mixed', 'ميكس جبن', 'كريب متنوع', 75.00, null, 'available', 17),
  ('cx4', 'crepe-mixed', 'تونة', 'كريب متنوع', 80.00, null, 'available', 18),
  ('cx5', 'crepe-mixed', 'بسطرمة', 'كريب متنوع', 90.00, null, 'available', 19),
  ('ct1', 'crepe-tuscanini', 'دوز كباب', 'كريب توسكانيني', 115.00, null, 'available', 20),
  ('ct2', 'crepe-tuscanini', 'دوز كرانشي', 'كريب توسكانيني', 125.00, null, 'available', 21),
  ('ct3', 'crepe-tuscanini', 'تشيكن فاير', 'كريب توسكانيني', 125.00, null, 'available', 22),
  ('ct4', 'crepe-tuscanini', 'تشيكن رانش', 'كريب توسكانيني', 105.00, null, 'available', 23),
  ('ct5', 'crepe-tuscanini', 'سوبريم', 'كريب توسكانيني', 120.00, null, 'available', 24),
  ('ct6', 'crepe-tuscanini', 'ميكس بيف', 'كريب توسكانيني', 110.00, null, 'available', 25),
  ('ct7', 'crepe-tuscanini', 'تشيكن أوميجا', 'كريب توسكانيني', 125.00, null, 'available', 26),
  ('ct8', 'crepe-tuscanini', 'تشيكن باربكيو', 'كريب توسكانيني', 120.00, null, 'available', 27),
  ('ct9', 'crepe-tuscanini', 'توب برجر', 'كريب توسكانيني', 120.00, null, 'available', 28),
  ('ct10', 'crepe-tuscanini', 'سيراتشا', 'كريب توسكانيني', 135.00, null, 'available', 29),
  ('ct11', 'crepe-tuscanini', 'ميكس مدخنات', 'كريب توسكانيني', 125.00, null, 'available', 30),
  ('ct12', 'crepe-tuscanini', 'بيف ميجا', 'كريب توسكانيني', 120.00, null, 'available', 31),
  ('ct13', 'crepe-tuscanini', 'لولي بوم', 'كريب توسكانيني', 125.00, null, 'available', 32),
  ('ct14', 'crepe-tuscanini', 'تركي بيف', 'كريب توسكانيني', 120.00, null, 'available', 33),
  ('ct15', 'crepe-tuscanini', 'تشيكن روكت', 'كريب توسكانيني', 130.00, null, 'available', 34),
  ('cs1', 'crepe-sweet', 'كريب نوتيلا', 'كريب حلو', 35.00, null, 'available', 35),
  ('cs2', 'crepe-sweet', 'كريب وايت', 'كريب حلو', 40.00, null, 'available', 36),
  ('cs3', 'crepe-sweet', 'كريب لوتس', 'كريب حلو', 45.00, null, 'available', 37),
  ('pm1', 'pizza-meat', 'برجر', 'بيتزا لحوم', 120.00, null, 'available', 38),
  ('pm2', 'pizza-meat', 'سوسيس', 'بيتزا لحوم', 120.00, null, 'available', 39),
  ('pm3', 'pizza-meat', 'مفروم', 'بيتزا لحوم', 145.00, null, 'available', 40),
  ('pm4', 'pizza-meat', 'شاورما لحم', 'بيتزا لحوم', 145.00, null, 'available', 41),
  ('pm5', 'pizza-meat', 'بيروني', 'بيتزا لحوم', 140.00, null, 'available', 42),
  ('pm6', 'pizza-meat', 'بسطرمة', 'بيتزا لحوم', 170.00, null, 'available', 43),
  ('pm7', 'pizza-meat', 'ميكس لحوم', 'بيتزا لحوم', 135.00, null, 'available', 44),
  ('pc1', 'pizza-chicken', 'شاورما فراخ', 'بيتزا فراخ', 130.00, null, 'available', 45),
  ('pc2', 'pizza-chicken', 'زينجر', 'بيتزا فراخ', 140.00, null, 'available', 46),
  ('pc3', 'pizza-chicken', 'شيش', 'بيتزا فراخ', 130.00, null, 'available', 47),
  ('pc4', 'pizza-chicken', 'استربس', 'بيتزا فراخ', 130.00, null, 'available', 48),
  ('pc5', 'pizza-chicken', 'ميكس فراخ', 'بيتزا فراخ', 155.00, null, 'available', 49),
  ('px1', 'pizza-mixed', 'مارجريتا', 'بيتزا متنوع', 90.00, null, 'available', 50),
  ('px2', 'pizza-mixed', 'ميكس جبن', 'بيتزا متنوع', 120.00, null, 'available', 51),
  ('px3', 'pizza-mixed', 'تونة', 'بيتزا متنوع', 140.00, null, 'available', 52),
  ('px4', 'pizza-mixed', 'مشروم', 'بيتزا متنوع', 120.00, null, 'available', 53),
  ('pt1', 'pizza-tuscanini', 'تشيكن رانش', 'بيتزا توسكانيني', 140.00, null, 'available', 54),
  ('pt2', 'pizza-tuscanini', 'تشيكن باربكيو', 'بيتزا توسكانيني', 140.00, null, 'available', 55),
  ('pt3', 'pizza-tuscanini', 'الفريدو', 'بيتزا توسكانيني', 140.00, null, 'available', 56),
  ('pt4', 'pizza-tuscanini', 'تشيكن فاير', 'بيتزا توسكانيني', 155.00, null, 'available', 57),
  ('pt5', 'pizza-tuscanini', 'تشيكن تكساس', 'بيتزا توسكانيني', 145.00, null, 'available', 58),
  ('pt6', 'pizza-tuscanini', 'الباستشيو', 'بيتزا توسكانيني', 150.00, null, 'available', 59),
  ('pt7', 'pizza-tuscanini', 'دوز كباب', 'بيتزا توسكانيني', 150.00, null, 'available', 60),
  ('pt8', 'pizza-tuscanini', 'سجق كيري', 'بيتزا توسكانيني', 130.00, null, 'available', 61),
  ('pt9', 'pizza-tuscanini', 'توسكانيني تشيكن', 'بيتزا توسكانيني', 320.00, null, 'available', 62),
  ('pt10', 'pizza-tuscanini', 'توسكانيني بيف', 'بيتزا توسكانيني', 340.00, null, 'available', 63),
  ('pa1', 'pasta', 'نجرسكو', 'باستا', 110.00, null, 'available', 64),
  ('pa2', 'pasta', 'جلاكسي', 'باستا', 115.00, null, 'available', 65),
  ('pa3', 'pasta', 'استربس رانش', 'باستا', 120.00, null, 'available', 66),
  ('pa4', 'pasta', 'زينجر شيدر', 'باستا', 125.00, null, 'available', 67),
  ('pa5', 'pasta', 'بشاميل', 'باستا', 115.00, null, 'available', 68),
  ('pa6', 'pasta', 'سجق', 'باستا', 90.00, null, 'available', 69),
  ('pa7', 'pasta', 'عشاق جبن', 'باستا', 135.00, null, 'available', 70),
  ('pa8', 'pasta', 'دوز كباب', 'باستا', 130.00, null, 'available', 71),
  ('pa9', 'pasta', 'الفريدو', 'باستا', 110.00, null, 'available', 72),
  ('pa10', 'pasta', 'سوسيس او برجر', 'باستا', 90.00, null, 'available', 73),
  ('pa11', 'pasta', 'ميكس فراخ', 'باستا', 140.00, null, 'available', 74),
  ('pa12', 'pasta', 'ميكس لحوم', 'باستا', 130.00, null, 'available', 75),
  ('sf1', 'sandwiches-french', 'شاورما فراخ/شيش', 'ساندوتشات فرنساوي', 65.00, null, 'available', 76),
  ('sf2', 'sandwiches-french', 'زينجر سوبريم', 'ساندوتشات فرنساوي', 85.00, null, 'available', 77),
  ('sf3', 'sandwiches-french', 'سوسيس ميكسكانو', 'ساندوتشات فرنساوي', 55.00, null, 'available', 78),
  ('sf4', 'sandwiches-french', 'شاورما لحم', 'ساندوتشات فرنساوي', 70.00, null, 'available', 79),
  ('sf5', 'sandwiches-french', 'فاهيتا فراخ / لحم', 'ساندوتشات فرنساوي', 80.00, null, 'available', 80),
  ('sf6', 'sandwiches-french', 'بوم فريت', 'ساندوتشات فرنساوي', 30.00, null, 'available', 81),
  ('sk1', 'sandwiches-kaiser', 'كايزر', 'ساندوتشات كيزر', 65.00, null, 'available', 82),
  ('sk2', 'sandwiches-kaiser', 'تشيز برجر', 'ساندوتشات كيزر', 85.00, null, 'available', 83),
  ('sk3', 'sandwiches-kaiser', 'توب برجر', 'ساندوتشات كيزر', 100.00, null, 'available', 84),
  ('sk4', 'sandwiches-kaiser', 'سموكي زينجر', 'ساندوتشات كيزر', 95.00, null, 'available', 85),
  ('sk5', 'sandwiches-kaiser', 'تشيكن فاير', 'ساندوتشات كيزر', 115.00, null, 'available', 86),
  ('sk6', 'sandwiches-kaiser', 'توسكانيني', 'ساندوتشات كيزر', 140.00, null, 'available', 87),
  ('ap1', 'appetizers', 'باكت بطاطس', 'مقبلات', 25.00, null, 'available', 88),
  ('ap2', 'appetizers', 'باكت كرانشي', 'مقبلات', 15.00, null, 'available', 89),
  ('ap3', 'appetizers', 'حلقات بصل', 'مقبلات', 45.00, null, 'available', 90),
  ('ap4', 'appetizers', 'استيك موزاريلا', 'مقبلات', 60.00, null, 'available', 91),
  ('ap5', 'appetizers', 'بطاطس شيدر / موزاريلا', 'مقبلات', 45.00, null, 'available', 92),
  ('ap6', 'appetizers', 'كرسبي فرايز', 'مقبلات', 75.00, null, 'available', 93),
  ('ap7', 'appetizers', 'كول سلو', 'مقبلات', 15.00, null, 'available', 94),
  ('ap8', 'appetizers', 'بطاطس متبلة', 'مقبلات', 15.00, null, 'available', 95),
  ('ap9', 'appetizers', 'تومية', 'مقبلات', 15.00, null, 'available', 96),
  ('ap10', 'appetizers', 'مخلل', 'مقبلات', 15.00, null, 'available', 97),
  ('dr1', 'drinks', 'مياه معدنية صغير', 'مشروبات', 10.00, null, 'available', 98),
  ('dr2', 'drinks', 'مياه معدنية كبير', 'مشروبات', 15.00, null, 'available', 99),
  ('dr3', 'drinks', 'بيبسي', 'مشروبات', 25.00, null, 'available', 100),
  ('dr4', 'drinks', 'سفن', 'مشروبات', 25.00, null, 'available', 101),
  ('dr5', 'drinks', 'تويست', 'مشروبات', 25.00, null, 'available', 102),
  ('dr6', 'drinks', 'فيروز', 'مشروبات', 25.00, null, 'available', 103),
  ('wf1', 'waffle', 'وافل نوتيلا', 'وافل', 60.00, null, 'available', 104),
  ('wf2', 'waffle', 'وافل وايت', 'وافل', 65.00, null, 'available', 105),
  ('wf3', 'waffle', 'وافل لوتس', 'وافل', 70.00, null, 'available', 106),
  ('ca1', 'crepe-addons', 'موتزاريلا', 'إضافات كريب', 20.00, null, 'available', 107),
  ('ca2', 'crepe-addons', 'رومي', 'إضافات كريب', 20.00, null, 'available', 108),
  ('ca3', 'crepe-addons', 'شيدر', 'إضافات كريب', 15.00, null, 'available', 109),
  ('ca4', 'crepe-addons', 'كونو', 'إضافات كريب', 25.00, null, 'available', 110),
  ('ca5', 'crepe-addons', 'رول', 'إضافات كريب', 25.00, null, 'available', 111),
  ('ca6', 'crepe-addons', 'صوصات', 'إضافات كريب', 15.00, null, 'available', 112);

update public.products as p
set
  category_id = mc.id,
  name_ar = sp.name_ar,
  description_ar = sp.description_ar,
  price_from = sp.price_from,
  base_price = sp.base_price,
  availability = sp.availability,
  sort_order = sp.sort_order,
  is_active = true
from seed_products sp
join public.menu_categories mc on mc.slug = sp.category_slug
where p.legacy_id = sp.legacy_id;

insert into public.products (legacy_id, category_id, name_ar, description_ar, price_from, base_price, availability, sort_order, is_active)
select sp.legacy_id, mc.id, sp.name_ar, sp.description_ar, sp.price_from, sp.base_price, sp.availability, sp.sort_order, true
from seed_products sp
join public.menu_categories mc on mc.slug = sp.category_slug
where not exists (
  select 1
  from public.products p
  where p.legacy_id = sp.legacy_id
);

create temporary table seed_product_sizes (
  product_legacy_id text not null,
  legacy_id text not null,
  label_ar text not null,
  price numeric(10,2) not null,
  sort_order integer not null
) on commit drop;

insert into seed_product_sizes (product_legacy_id, legacy_id, label_ar, price, sort_order) values
  ('cm1', 'cm1:small', 'صغير', 40.00, 0),
  ('cm1', 'cm1:large', 'كبير', 60.00, 1),
  ('cm1', 'cm1:jumbo', 'جامبو', 75.00, 2),
  ('cm2', 'cm2:small', 'صغير', 40.00, 0),
  ('cm2', 'cm2:large', 'كبير', 60.00, 1),
  ('cm2', 'cm2:jumbo', 'جامبو', 75.00, 2),
  ('cm3', 'cm3:small', 'صغير', 60.00, 0),
  ('cm3', 'cm3:large', 'كبير', 75.00, 1),
  ('cm3', 'cm3:jumbo', 'جامبو', 85.00, 2),
  ('cm4', 'cm4:large', 'كبير', 60.00, 0),
  ('cm5', 'cm5:large', 'كبير', 75.00, 0),
  ('cm6', 'cm6:large', 'كبير', 85.00, 0),
  ('cm7', 'cm7:large', 'كبير', 85.00, 0),
  ('cm8', 'cm8:large', 'كبير', 95.00, 0),
  ('cc1', 'cc1:small', 'صغير', 50.00, 0),
  ('cc1', 'cc1:large', 'كبير', 80.00, 1),
  ('cc1', 'cc1:jumbo', 'جامبو', 100.00, 2),
  ('cc2', 'cc2:small', 'صغير', 70.00, 0),
  ('cc2', 'cc2:large', 'كبير', 90.00, 1),
  ('cc2', 'cc2:jumbo', 'جامبو', 120.00, 2),
  ('cc3', 'cc3:small', 'صغير', 55.00, 0),
  ('cc3', 'cc3:large', 'كبير', 85.00, 1),
  ('cc3', 'cc3:jumbo', 'جامبو', 110.00, 2),
  ('cc4', 'cc4:small', 'صغير', 50.00, 0),
  ('cc4', 'cc4:large', 'كبير', 80.00, 1),
  ('cc4', 'cc4:jumbo', 'جامبو', 100.00, 2),
  ('cc5', 'cc5:small', 'صغير', 50.00, 0),
  ('cc5', 'cc5:large', 'كبير', 80.00, 1),
  ('cc5', 'cc5:jumbo', 'جامبو', 100.00, 2),
  ('cc6', 'cc6:small', 'صغير', 55.00, 0),
  ('cc6', 'cc6:large', 'كبير', 85.00, 1),
  ('cc6', 'cc6:jumbo', 'جامبو', 110.00, 2),
  ('cc7', 'cc7:small', 'صغير', 95.00, 0),
  ('cx1', 'cx1:small', 'صغير', 40.00, 0),
  ('cx1', 'cx1:large', 'كبير', 50.00, 1),
  ('cx1', 'cx1:jumbo', 'جامبو', 60.00, 2),
  ('cx2', 'cx2:small', 'صغير', 70.00, 0),
  ('cx3', 'cx3:small', 'صغير', 75.00, 0),
  ('cx4', 'cx4:single', 'سعر واحد', 80.00, 0),
  ('cx5', 'cx5:single', 'سعر واحد', 90.00, 0),
  ('ct1', 'ct1:single', 'سعر واحد', 115.00, 0),
  ('ct2', 'ct2:single', 'سعر واحد', 125.00, 0),
  ('ct3', 'ct3:single', 'سعر واحد', 125.00, 0),
  ('ct4', 'ct4:single', 'سعر واحد', 105.00, 0),
  ('ct5', 'ct5:single', 'سعر واحد', 120.00, 0),
  ('ct6', 'ct6:single', 'سعر واحد', 110.00, 0),
  ('ct7', 'ct7:single', 'سعر واحد', 125.00, 0),
  ('ct8', 'ct8:single', 'سعر واحد', 120.00, 0),
  ('ct9', 'ct9:single', 'سعر واحد', 120.00, 0),
  ('ct10', 'ct10:single', 'سعر واحد', 135.00, 0),
  ('ct11', 'ct11:single', 'سعر واحد', 125.00, 0),
  ('ct12', 'ct12:single', 'سعر واحد', 120.00, 0),
  ('ct13', 'ct13:single', 'سعر واحد', 125.00, 0),
  ('ct14', 'ct14:single', 'سعر واحد', 120.00, 0),
  ('ct15', 'ct15:single', 'سعر واحد', 130.00, 0),
  ('cs1', 'cs1:small', 'صغير', 35.00, 0),
  ('cs1', 'cs1:large', 'كبير', 55.00, 1),
  ('cs2', 'cs2:small', 'صغير', 40.00, 0),
  ('cs2', 'cs2:large', 'كبير', 60.00, 1),
  ('cs3', 'cs3:small', 'صغير', 45.00, 0),
  ('cs3', 'cs3:large', 'كبير', 65.00, 1),
  ('pm1', 'pm1:small', 'صغير', 120.00, 0),
  ('pm1', 'pm1:medium', 'وسط', 150.00, 1),
  ('pm1', 'pm1:large', 'كبير', 210.00, 2),
  ('pm1', 'pm1:family', 'فاميلي', 270.00, 3),
  ('pm2', 'pm2:small', 'صغير', 120.00, 0),
  ('pm2', 'pm2:medium', 'وسط', 150.00, 1),
  ('pm2', 'pm2:large', 'كبير', 210.00, 2),
  ('pm2', 'pm2:family', 'فاميلي', 270.00, 3),
  ('pm3', 'pm3:small', 'صغير', 145.00, 0),
  ('pm3', 'pm3:medium', 'وسط', 185.00, 1),
  ('pm3', 'pm3:large', 'كبير', 250.00, 2),
  ('pm3', 'pm3:family', 'فاميلي', 310.00, 3),
  ('pm4', 'pm4:small', 'صغير', 145.00, 0),
  ('pm4', 'pm4:medium', 'وسط', 185.00, 1),
  ('pm4', 'pm4:large', 'كبير', 250.00, 2),
  ('pm4', 'pm4:family', 'فاميلي', 310.00, 3),
  ('pm5', 'pm5:small', 'صغير', 140.00, 0),
  ('pm5', 'pm5:medium', 'وسط', 180.00, 1),
  ('pm5', 'pm5:large', 'كبير', 220.00, 2),
  ('pm5', 'pm5:family', 'فاميلي', 270.00, 3),
  ('pm6', 'pm6:small', 'صغير', 170.00, 0),
  ('pm6', 'pm6:medium', 'وسط', 210.00, 1),
  ('pm6', 'pm6:large', 'كبير', 270.00, 2),
  ('pm6', 'pm6:family', 'فاميلي', 325.00, 3),
  ('pm7', 'pm7:small', 'صغير', 135.00, 0),
  ('pm7', 'pm7:medium', 'وسط', 190.00, 1),
  ('pm7', 'pm7:large', 'كبير', 240.00, 2),
  ('pm7', 'pm7:family', 'فاميلي', 310.00, 3),
  ('pc1', 'pc1:small', 'صغير', 130.00, 0),
  ('pc1', 'pc1:medium', 'وسط', 180.00, 1),
  ('pc1', 'pc1:large', 'كبير', 230.00, 2),
  ('pc1', 'pc1:family', 'فاميلي', 310.00, 3),
  ('pc2', 'pc2:small', 'صغير', 140.00, 0),
  ('pc2', 'pc2:medium', 'وسط', 190.00, 1),
  ('pc2', 'pc2:large', 'كبير', 240.00, 2),
  ('pc2', 'pc2:family', 'فاميلي', 320.00, 3),
  ('pc3', 'pc3:small', 'صغير', 130.00, 0),
  ('pc3', 'pc3:medium', 'وسط', 180.00, 1),
  ('pc3', 'pc3:large', 'كبير', 230.00, 2),
  ('pc3', 'pc3:family', 'فاميلي', 310.00, 3),
  ('pc4', 'pc4:small', 'صغير', 130.00, 0),
  ('pc4', 'pc4:medium', 'وسط', 180.00, 1),
  ('pc4', 'pc4:large', 'كبير', 230.00, 2),
  ('pc4', 'pc4:family', 'فاميلي', 310.00, 3),
  ('pc5', 'pc5:small', 'صغير', 155.00, 0),
  ('pc5', 'pc5:medium', 'وسط', 195.00, 1),
  ('pc5', 'pc5:large', 'كبير', 250.00, 2),
  ('pc5', 'pc5:family', 'فاميلي', 315.00, 3),
  ('px1', 'px1:small', 'صغير', 90.00, 0),
  ('px1', 'px1:medium', 'وسط', 115.00, 1),
  ('px1', 'px1:large', 'كبير', 150.00, 2),
  ('px1', 'px1:family', 'فاميلي', 190.00, 3),
  ('px2', 'px2:small', 'صغير', 120.00, 0),
  ('px2', 'px2:medium', 'وسط', 150.00, 1),
  ('px2', 'px2:large', 'كبير', 190.00, 2),
  ('px2', 'px2:family', 'فاميلي', 250.00, 3),
  ('px3', 'px3:small', 'صغير', 140.00, 0),
  ('px3', 'px3:medium', 'وسط', 195.00, 1),
  ('px3', 'px3:large', 'كبير', 240.00, 2),
  ('px3', 'px3:family', 'فاميلي', 305.00, 3),
  ('px4', 'px4:small', 'صغير', 120.00, 0),
  ('px4', 'px4:medium', 'وسط', 150.00, 1),
  ('px4', 'px4:large', 'كبير', 180.00, 2),
  ('px4', 'px4:family', 'فاميلي', 230.00, 3),
  ('pt1', 'pt1:small', 'صغير', 140.00, 0),
  ('pt1', 'pt1:medium', 'وسط', 190.00, 1),
  ('pt1', 'pt1:large', 'كبير', 240.00, 2),
  ('pt1', 'pt1:family', 'فاميلي', 320.00, 3),
  ('pt2', 'pt2:small', 'صغير', 140.00, 0),
  ('pt2', 'pt2:medium', 'وسط', 190.00, 1),
  ('pt2', 'pt2:large', 'كبير', 240.00, 2),
  ('pt2', 'pt2:family', 'فاميلي', 320.00, 3),
  ('pt3', 'pt3:small', 'صغير', 140.00, 0),
  ('pt3', 'pt3:medium', 'وسط', 190.00, 1),
  ('pt3', 'pt3:large', 'كبير', 240.00, 2),
  ('pt3', 'pt3:family', 'فاميلي', 320.00, 3),
  ('pt4', 'pt4:small', 'صغير', 155.00, 0),
  ('pt4', 'pt4:medium', 'وسط', 205.00, 1),
  ('pt4', 'pt4:large', 'كبير', 255.00, 2),
  ('pt4', 'pt4:family', 'فاميلي', 330.00, 3),
  ('pt5', 'pt5:small', 'صغير', 145.00, 0),
  ('pt5', 'pt5:medium', 'وسط', 195.00, 1),
  ('pt5', 'pt5:large', 'كبير', 260.00, 2),
  ('pt5', 'pt5:family', 'فاميلي', 335.00, 3),
  ('pt6', 'pt6:small', 'صغير', 150.00, 0),
  ('pt6', 'pt6:medium', 'وسط', 210.00, 1),
  ('pt6', 'pt6:large', 'كبير', 270.00, 2),
  ('pt6', 'pt6:family', 'فاميلي', 350.00, 3),
  ('pt7', 'pt7:small', 'صغير', 150.00, 0),
  ('pt7', 'pt7:medium', 'وسط', 190.00, 1),
  ('pt7', 'pt7:large', 'كبير', 260.00, 2),
  ('pt7', 'pt7:family', 'فاميلي', 335.00, 3),
  ('pt8', 'pt8:small', 'صغير', 130.00, 0),
  ('pt8', 'pt8:medium', 'وسط', 170.00, 1),
  ('pt8', 'pt8:large', 'كبير', 215.00, 2),
  ('pt8', 'pt8:family', 'فاميلي', 280.00, 3),
  ('pt9', 'pt9:large', 'كبير', 320.00, 0),
  ('pt10', 'pt10:large', 'كبير', 340.00, 0),
  ('pa1', 'pa1:single', 'سعر واحد', 110.00, 0),
  ('pa2', 'pa2:single', 'سعر واحد', 115.00, 0),
  ('pa3', 'pa3:single', 'سعر واحد', 120.00, 0),
  ('pa4', 'pa4:single', 'سعر واحد', 125.00, 0),
  ('pa5', 'pa5:single', 'سعر واحد', 115.00, 0),
  ('pa6', 'pa6:single', 'سعر واحد', 90.00, 0),
  ('pa7', 'pa7:single', 'سعر واحد', 135.00, 0),
  ('pa8', 'pa8:single', 'سعر واحد', 130.00, 0),
  ('pa9', 'pa9:single', 'سعر واحد', 110.00, 0),
  ('pa10', 'pa10:single', 'سعر واحد', 90.00, 0),
  ('pa11', 'pa11:single', 'سعر واحد', 140.00, 0),
  ('pa12', 'pa12:single', 'سعر واحد', 130.00, 0),
  ('sf1', 'sf1:single', 'سعر واحد', 65.00, 0),
  ('sf2', 'sf2:single', 'سعر واحد', 85.00, 0),
  ('sf3', 'sf3:single', 'سعر واحد', 55.00, 0),
  ('sf4', 'sf4:single', 'سعر واحد', 70.00, 0),
  ('sf5', 'sf5:single', 'سعر واحد', 80.00, 0),
  ('sf6', 'sf6:single', 'سعر واحد', 30.00, 0),
  ('sk1', 'sk1:single', 'سعر واحد', 65.00, 0),
  ('sk2', 'sk2:single', 'سعر واحد', 85.00, 0),
  ('sk3', 'sk3:single', 'سعر واحد', 100.00, 0),
  ('sk4', 'sk4:single', 'سعر واحد', 95.00, 0),
  ('sk5', 'sk5:single', 'سعر واحد', 115.00, 0),
  ('sk6', 'sk6:single', 'سعر واحد', 140.00, 0),
  ('ap1', 'ap1:single', 'سعر واحد', 25.00, 0),
  ('ap2', 'ap2:single', 'سعر واحد', 15.00, 0),
  ('ap3', 'ap3:single', 'سعر واحد', 45.00, 0),
  ('ap4', 'ap4:single', 'سعر واحد', 60.00, 0),
  ('ap5', 'ap5:single', 'سعر واحد', 45.00, 0),
  ('ap6', 'ap6:single', 'سعر واحد', 75.00, 0),
  ('ap7', 'ap7:single', 'سعر واحد', 15.00, 0),
  ('ap8', 'ap8:single', 'سعر واحد', 15.00, 0),
  ('ap9', 'ap9:single', 'سعر واحد', 15.00, 0),
  ('ap10', 'ap10:single', 'سعر واحد', 15.00, 0),
  ('dr1', 'dr1:single', 'سعر واحد', 10.00, 0),
  ('dr2', 'dr2:single', 'سعر واحد', 15.00, 0),
  ('dr3', 'dr3:single', 'سعر واحد', 25.00, 0),
  ('dr4', 'dr4:single', 'سعر واحد', 25.00, 0),
  ('dr5', 'dr5:single', 'سعر واحد', 25.00, 0),
  ('dr6', 'dr6:single', 'سعر واحد', 25.00, 0),
  ('wf1', 'wf1:single', 'سعر واحد', 60.00, 0),
  ('wf2', 'wf2:single', 'سعر واحد', 65.00, 0),
  ('wf3', 'wf3:single', 'سعر واحد', 70.00, 0),
  ('ca1', 'ca1:single', 'سعر واحد', 20.00, 0),
  ('ca2', 'ca2:single', 'سعر واحد', 20.00, 0),
  ('ca3', 'ca3:single', 'سعر واحد', 15.00, 0),
  ('ca4', 'ca4:single', 'سعر واحد', 25.00, 0),
  ('ca5', 'ca5:single', 'سعر واحد', 25.00, 0),
  ('ca6', 'ca6:single', 'سعر واحد', 15.00, 0);

insert into public.product_sizes (product_id, legacy_id, label_ar, price, sort_order, is_active)
select p.id, sps.legacy_id, sps.label_ar, sps.price, sps.sort_order, true
from seed_product_sizes sps
join public.products p on p.legacy_id = sps.product_legacy_id
on conflict (product_id, legacy_id) do update set
  label_ar = excluded.label_ar,
  price = excluded.price,
  sort_order = excluded.sort_order,
  is_active = true;

create temporary table seed_product_addons (
  legacy_id text not null,
  label_ar text not null,
  price numeric(10,2) not null
) on commit drop;

insert into seed_product_addons (legacy_id, label_ar, price) values
  ('addon-mozzarella', 'موتزاريلا', 20.00),
  ('addon-roumy', 'رومي', 20.00),
  ('addon-cheddar', 'شيدر', 15.00),
  ('addon-cono', 'كونو', 25.00),
  ('addon-roll', 'رول', 25.00),
  ('addon-sauces', 'صوصات', 15.00);

update public.product_addons pa
set
  label_ar = spa.label_ar,
  price = spa.price,
  is_active = true
from seed_product_addons spa
where pa.legacy_id = spa.legacy_id;

insert into public.product_addons (legacy_id, label_ar, price, is_active)
select spa.legacy_id, spa.label_ar, spa.price, true
from seed_product_addons spa
where not exists (
  select 1
  from public.product_addons pa
  where pa.legacy_id = spa.legacy_id
);

create temporary table seed_product_addon_links (
  product_legacy_id text not null,
  addon_legacy_id text not null
) on commit drop;

insert into seed_product_addon_links (product_legacy_id, addon_legacy_id) values
  ('cm1', 'addon-mozzarella'),
  ('cm1', 'addon-roumy'),
  ('cm1', 'addon-cheddar'),
  ('cm1', 'addon-cono'),
  ('cm1', 'addon-roll'),
  ('cm1', 'addon-sauces'),
  ('cm2', 'addon-mozzarella'),
  ('cm2', 'addon-roumy'),
  ('cm2', 'addon-cheddar'),
  ('cm2', 'addon-cono'),
  ('cm2', 'addon-roll'),
  ('cm2', 'addon-sauces'),
  ('cm3', 'addon-mozzarella'),
  ('cm3', 'addon-roumy'),
  ('cm3', 'addon-cheddar'),
  ('cm3', 'addon-cono'),
  ('cm3', 'addon-roll'),
  ('cm3', 'addon-sauces'),
  ('cm4', 'addon-mozzarella'),
  ('cm4', 'addon-roumy'),
  ('cm4', 'addon-cheddar'),
  ('cm4', 'addon-cono'),
  ('cm4', 'addon-roll'),
  ('cm4', 'addon-sauces'),
  ('cm5', 'addon-mozzarella'),
  ('cm5', 'addon-roumy'),
  ('cm5', 'addon-cheddar'),
  ('cm5', 'addon-cono'),
  ('cm5', 'addon-roll'),
  ('cm5', 'addon-sauces'),
  ('cm6', 'addon-mozzarella'),
  ('cm6', 'addon-roumy'),
  ('cm6', 'addon-cheddar'),
  ('cm6', 'addon-cono'),
  ('cm6', 'addon-roll'),
  ('cm6', 'addon-sauces'),
  ('cm7', 'addon-mozzarella'),
  ('cm7', 'addon-roumy'),
  ('cm7', 'addon-cheddar'),
  ('cm7', 'addon-cono'),
  ('cm7', 'addon-roll'),
  ('cm7', 'addon-sauces'),
  ('cm8', 'addon-mozzarella'),
  ('cm8', 'addon-roumy'),
  ('cm8', 'addon-cheddar'),
  ('cm8', 'addon-cono'),
  ('cm8', 'addon-roll'),
  ('cm8', 'addon-sauces'),
  ('cc1', 'addon-mozzarella'),
  ('cc1', 'addon-roumy'),
  ('cc1', 'addon-cheddar'),
  ('cc1', 'addon-cono'),
  ('cc1', 'addon-roll'),
  ('cc1', 'addon-sauces'),
  ('cc2', 'addon-mozzarella'),
  ('cc2', 'addon-roumy'),
  ('cc2', 'addon-cheddar'),
  ('cc2', 'addon-cono'),
  ('cc2', 'addon-roll'),
  ('cc2', 'addon-sauces'),
  ('cc3', 'addon-mozzarella'),
  ('cc3', 'addon-roumy'),
  ('cc3', 'addon-cheddar'),
  ('cc3', 'addon-cono'),
  ('cc3', 'addon-roll'),
  ('cc3', 'addon-sauces'),
  ('cc4', 'addon-mozzarella'),
  ('cc4', 'addon-roumy'),
  ('cc4', 'addon-cheddar'),
  ('cc4', 'addon-cono'),
  ('cc4', 'addon-roll'),
  ('cc4', 'addon-sauces'),
  ('cc5', 'addon-mozzarella'),
  ('cc5', 'addon-roumy'),
  ('cc5', 'addon-cheddar'),
  ('cc5', 'addon-cono'),
  ('cc5', 'addon-roll'),
  ('cc5', 'addon-sauces'),
  ('cc6', 'addon-mozzarella'),
  ('cc6', 'addon-roumy'),
  ('cc6', 'addon-cheddar'),
  ('cc6', 'addon-cono'),
  ('cc6', 'addon-roll'),
  ('cc6', 'addon-sauces'),
  ('cc7', 'addon-mozzarella'),
  ('cc7', 'addon-roumy'),
  ('cc7', 'addon-cheddar'),
  ('cc7', 'addon-cono'),
  ('cc7', 'addon-roll'),
  ('cc7', 'addon-sauces'),
  ('cx1', 'addon-mozzarella'),
  ('cx1', 'addon-roumy'),
  ('cx1', 'addon-cheddar'),
  ('cx1', 'addon-cono'),
  ('cx1', 'addon-roll'),
  ('cx1', 'addon-sauces'),
  ('cx2', 'addon-mozzarella'),
  ('cx2', 'addon-roumy'),
  ('cx2', 'addon-cheddar'),
  ('cx2', 'addon-cono'),
  ('cx2', 'addon-roll'),
  ('cx2', 'addon-sauces'),
  ('cx3', 'addon-mozzarella'),
  ('cx3', 'addon-roumy'),
  ('cx3', 'addon-cheddar'),
  ('cx3', 'addon-cono'),
  ('cx3', 'addon-roll'),
  ('cx3', 'addon-sauces'),
  ('cx4', 'addon-mozzarella'),
  ('cx4', 'addon-roumy'),
  ('cx4', 'addon-cheddar'),
  ('cx4', 'addon-cono'),
  ('cx4', 'addon-roll'),
  ('cx4', 'addon-sauces'),
  ('cx5', 'addon-mozzarella'),
  ('cx5', 'addon-roumy'),
  ('cx5', 'addon-cheddar'),
  ('cx5', 'addon-cono'),
  ('cx5', 'addon-roll'),
  ('cx5', 'addon-sauces'),
  ('ct1', 'addon-mozzarella'),
  ('ct1', 'addon-roumy'),
  ('ct1', 'addon-cheddar'),
  ('ct1', 'addon-cono'),
  ('ct1', 'addon-roll'),
  ('ct1', 'addon-sauces'),
  ('ct2', 'addon-mozzarella'),
  ('ct2', 'addon-roumy'),
  ('ct2', 'addon-cheddar'),
  ('ct2', 'addon-cono'),
  ('ct2', 'addon-roll'),
  ('ct2', 'addon-sauces'),
  ('ct3', 'addon-mozzarella'),
  ('ct3', 'addon-roumy'),
  ('ct3', 'addon-cheddar'),
  ('ct3', 'addon-cono'),
  ('ct3', 'addon-roll'),
  ('ct3', 'addon-sauces'),
  ('ct4', 'addon-mozzarella'),
  ('ct4', 'addon-roumy'),
  ('ct4', 'addon-cheddar'),
  ('ct4', 'addon-cono'),
  ('ct4', 'addon-roll'),
  ('ct4', 'addon-sauces'),
  ('ct5', 'addon-mozzarella'),
  ('ct5', 'addon-roumy'),
  ('ct5', 'addon-cheddar'),
  ('ct5', 'addon-cono'),
  ('ct5', 'addon-roll'),
  ('ct5', 'addon-sauces'),
  ('ct6', 'addon-mozzarella'),
  ('ct6', 'addon-roumy'),
  ('ct6', 'addon-cheddar'),
  ('ct6', 'addon-cono'),
  ('ct6', 'addon-roll'),
  ('ct6', 'addon-sauces'),
  ('ct7', 'addon-mozzarella'),
  ('ct7', 'addon-roumy'),
  ('ct7', 'addon-cheddar'),
  ('ct7', 'addon-cono'),
  ('ct7', 'addon-roll'),
  ('ct7', 'addon-sauces'),
  ('ct8', 'addon-mozzarella'),
  ('ct8', 'addon-roumy'),
  ('ct8', 'addon-cheddar'),
  ('ct8', 'addon-cono'),
  ('ct8', 'addon-roll'),
  ('ct8', 'addon-sauces'),
  ('ct9', 'addon-mozzarella'),
  ('ct9', 'addon-roumy'),
  ('ct9', 'addon-cheddar'),
  ('ct9', 'addon-cono'),
  ('ct9', 'addon-roll'),
  ('ct9', 'addon-sauces'),
  ('ct10', 'addon-mozzarella'),
  ('ct10', 'addon-roumy'),
  ('ct10', 'addon-cheddar'),
  ('ct10', 'addon-cono'),
  ('ct10', 'addon-roll'),
  ('ct10', 'addon-sauces'),
  ('ct11', 'addon-mozzarella'),
  ('ct11', 'addon-roumy'),
  ('ct11', 'addon-cheddar'),
  ('ct11', 'addon-cono'),
  ('ct11', 'addon-roll'),
  ('ct11', 'addon-sauces'),
  ('ct12', 'addon-mozzarella'),
  ('ct12', 'addon-roumy'),
  ('ct12', 'addon-cheddar'),
  ('ct12', 'addon-cono'),
  ('ct12', 'addon-roll'),
  ('ct12', 'addon-sauces'),
  ('ct13', 'addon-mozzarella'),
  ('ct13', 'addon-roumy'),
  ('ct13', 'addon-cheddar'),
  ('ct13', 'addon-cono'),
  ('ct13', 'addon-roll'),
  ('ct13', 'addon-sauces'),
  ('ct14', 'addon-mozzarella'),
  ('ct14', 'addon-roumy'),
  ('ct14', 'addon-cheddar'),
  ('ct14', 'addon-cono'),
  ('ct14', 'addon-roll'),
  ('ct14', 'addon-sauces'),
  ('ct15', 'addon-mozzarella'),
  ('ct15', 'addon-roumy'),
  ('ct15', 'addon-cheddar'),
  ('ct15', 'addon-cono'),
  ('ct15', 'addon-roll'),
  ('ct15', 'addon-sauces');

insert into public.product_addon_links (product_id, addon_id)
select distinct p.id, pa.id
from seed_product_addon_links spal
join public.products p on p.legacy_id = spal.product_legacy_id
join public.product_addons pa on pa.legacy_id = spal.addon_legacy_id
on conflict (product_id, addon_id) do nothing;

insert into public.site_settings (id, whatsapp_order_number, phone_primary, phone_secondary, address_ar, facebook_url)
values (1, '01004747286', '01108006463', '01200364848', 'شارع البحر - سور نادي توليب أمام النادي الرياضي', 'https://www.facebook.com/share/1LHWJ9JpXZ/')
on conflict (id) do update set
  whatsapp_order_number = excluded.whatsapp_order_number,
  phone_primary = excluded.phone_primary,
  phone_secondary = excluded.phone_secondary,
  address_ar = excluded.address_ar,
  facebook_url = excluded.facebook_url;

commit;
