import type { MenuCategory, MenuItem } from '@/types/menu';
import type { Offer } from '@/types/offers';

const crepeAddons = [
  { id: 'addon-mozzarella', label: 'موتزاريلا', price: 20 },
  { id: 'addon-roumy', label: 'رومي', price: 20 },
  { id: 'addon-cheddar', label: 'شيدر', price: 15 },
  { id: 'addon-cono', label: 'كونو', price: 25 },
  { id: 'addon-roll', label: 'رول', price: 25 },
  { id: 'addon-sauces', label: 'صوصات', price: 15 },
];

export const menuCategories: MenuCategory[] = [
  { id: 'c1', name: 'كريب لحوم', slug: 'crepe-meat', description: 'منيو توسكانيني' },
  { id: 'c2', name: 'كريب فراخ', slug: 'crepe-chicken', description: 'منيو توسكانيني' },
  { id: 'c3', name: 'كريب متنوع', slug: 'crepe-mixed', description: 'منيو توسكانيني' },
  { id: 'c4', name: 'كريب توسكانيني', slug: 'crepe-tuscanini', description: 'منيو توسكانيني' },
  { id: 'c5', name: 'كريب حلو', slug: 'crepe-sweet', description: 'منيو توسكانيني' },
  { id: 'c6', name: 'بيتزا لحوم', slug: 'pizza-meat', description: 'منيو توسكانيني' },
  { id: 'c7', name: 'بيتزا فراخ', slug: 'pizza-chicken', description: 'منيو توسكانيني' },
  { id: 'c8', name: 'بيتزا متنوع', slug: 'pizza-mixed', description: 'منيو توسكانيني' },
  { id: 'c9', name: 'بيتزا توسكانيني', slug: 'pizza-tuscanini', description: 'منيو توسكانيني' },
  { id: 'c10', name: 'باستا', slug: 'pasta', description: 'منيو توسكانيني' },
  { id: 'c11', name: 'ساندوتشات فرنساوي', slug: 'sandwiches-french', description: 'منيو توسكانيني' },
  { id: 'c12', name: 'ساندوتشات كيزر', slug: 'sandwiches-kaiser', description: 'منيو توسكانيني' },
  { id: 'c13', name: 'مقبلات', slug: 'appetizers', description: 'منيو توسكانيني' },
  { id: 'c14', name: 'مشروبات', slug: 'drinks', description: 'منيو توسكانيني' },
  { id: 'c15', name: 'وافل', slug: 'waffle', description: 'منيو توسكانيني' },
  { id: 'c16', name: 'إضافات كريب', slug: 'crepe-addons', description: 'منيو توسكانيني' },
];

export const featuredItems: MenuItem[] = [
  {
    id: 'cm1',
    name: 'برجر',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 40,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 40 },
      { id: 'large', label: 'كبير', price: 60 },
      { id: 'jumbo', label: 'جامبو', price: 75 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cm2',
    name: 'سوسيس',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 40,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 40 },
      { id: 'large', label: 'كبير', price: 60 },
      { id: 'jumbo', label: 'جامبو', price: 75 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cm3',
    name: 'ميكس لحوم برجر ع سوسيس',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 60,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 60 },
      { id: 'large', label: 'كبير', price: 75 },
      { id: 'jumbo', label: 'جامبو', price: 85 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cm4',
    name: 'سجق',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 60,
    availability: 'available',
    sizes: [{ id: 'large', label: 'كبير', price: 60 }],
    addons: crepeAddons,
  },
  {
    id: 'cm5',
    name: 'كفتة',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 75,
    availability: 'available',
    sizes: [{ id: 'large', label: 'كبير', price: 75 }],
    addons: crepeAddons,
  },
  {
    id: 'cm6',
    name: 'مفروم',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 85,
    availability: 'available',
    sizes: [{ id: 'large', label: 'كبير', price: 85 }],
    addons: crepeAddons,
  },
  {
    id: 'cm7',
    name: 'شاورما لحم',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 85,
    availability: 'available',
    sizes: [{ id: 'large', label: 'كبير', price: 85 }],
    addons: crepeAddons,
  },
  {
    id: 'cm8',
    name: 'فاهيتا لحم',
    categorySlug: 'crepe-meat',
    description: 'كريب لحوم',
    priceFrom: 95,
    availability: 'available',
    sizes: [{ id: 'large', label: 'كبير', price: 95 }],
    addons: crepeAddons,
  },
  {
    id: 'cc1',
    name: 'شاورما فراخ',
    categorySlug: 'crepe-chicken',
    description: 'كريب فراخ',
    priceFrom: 50,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 50 },
      { id: 'large', label: 'كبير', price: 80 },
      { id: 'jumbo', label: 'جامبو', price: 100 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cc2',
    name: 'فاهيتا فراخ',
    categorySlug: 'crepe-chicken',
    description: 'كريب فراخ',
    priceFrom: 70,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 70 },
      { id: 'large', label: 'كبير', price: 90 },
      { id: 'jumbo', label: 'جامبو', price: 120 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cc3',
    name: 'شيش',
    categorySlug: 'crepe-chicken',
    description: 'كريب فراخ',
    priceFrom: 55,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 55 },
      { id: 'large', label: 'كبير', price: 85 },
      { id: 'jumbo', label: 'جامبو', price: 110 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cc4',
    name: 'استربس',
    categorySlug: 'crepe-chicken',
    description: 'كريب فراخ',
    priceFrom: 50,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 50 },
      { id: 'large', label: 'كبير', price: 80 },
      { id: 'jumbo', label: 'جامبو', price: 100 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cc5',
    name: 'بانيه',
    categorySlug: 'crepe-chicken',
    description: 'كريب فراخ',
    priceFrom: 50,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 50 },
      { id: 'large', label: 'كبير', price: 80 },
      { id: 'jumbo', label: 'جامبو', price: 100 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cc6',
    name: 'زينجر',
    categorySlug: 'crepe-chicken',
    description: 'كريب فراخ',
    priceFrom: 55,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 55 },
      { id: 'large', label: 'كبير', price: 85 },
      { id: 'jumbo', label: 'جامبو', price: 110 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cc7',
    name: 'برجر ع بانيه',
    categorySlug: 'crepe-chicken',
    description: 'كريب فراخ',
    priceFrom: 95,
    availability: 'available',
    sizes: [{ id: 'small', label: 'صغير', price: 95 }],
    addons: crepeAddons,
  },
  {
    id: 'cx1',
    name: 'بطاطس',
    categorySlug: 'crepe-mixed',
    description: 'كريب متنوع',
    priceFrom: 40,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 40 },
      { id: 'large', label: 'كبير', price: 50 },
      { id: 'jumbo', label: 'جامبو', price: 60 },
    ],
    addons: crepeAddons,
  },
  {
    id: 'cx2',
    name: 'مشروم',
    categorySlug: 'crepe-mixed',
    description: 'كريب متنوع',
    priceFrom: 70,
    availability: 'available',
    sizes: [{ id: 'small', label: 'صغير', price: 70 }],
    addons: crepeAddons,
  },
  {
    id: 'cx3',
    name: 'ميكس جبن',
    categorySlug: 'crepe-mixed',
    description: 'كريب متنوع',
    priceFrom: 75,
    availability: 'available',
    sizes: [{ id: 'small', label: 'صغير', price: 75 }],
    addons: crepeAddons,
  },
  {
    id: 'cx4',
    name: 'تونة',
    categorySlug: 'crepe-mixed',
    description: 'كريب متنوع',
    priceFrom: 80,
    availability: 'available',
    sizes: [{ id: 'single', label: 'سعر واحد', price: 80 }],
    addons: crepeAddons,
  },
  {
    id: 'cx5',
    name: 'بسطرمة',
    categorySlug: 'crepe-mixed',
    description: 'كريب متنوع',
    priceFrom: 90,
    availability: 'available',
    sizes: [{ id: 'single', label: 'سعر واحد', price: 90 }],
    addons: crepeAddons,
  },
  {
    id: 'ct1',
    name: 'دوز كباب',
    categorySlug: 'crepe-tuscanini',
    description: 'كريب توسكانيني',
    priceFrom: 115,
    availability: 'available',
    sizes: [{ id: 'single', label: 'سعر واحد', price: 115 }],
    addons: crepeAddons,
  },
  { id: 'ct2', name: 'دوز كرانشي', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 125, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 125 }], addons: crepeAddons },
  { id: 'ct3', name: 'تشيكن فاير', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 125, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 125 }], addons: crepeAddons },
  { id: 'ct4', name: 'تشيكن رانش', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 105, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 105 }], addons: crepeAddons },
  { id: 'ct5', name: 'سوبريم', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 120, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 120 }], addons: crepeAddons },
  { id: 'ct6', name: 'ميكس بيف', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 110, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 110 }], addons: crepeAddons },
  { id: 'ct7', name: 'تشيكن أوميجا', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 125, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 125 }], addons: crepeAddons },
  { id: 'ct8', name: 'تشيكن باربكيو', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 120, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 120 }], addons: crepeAddons },
  { id: 'ct9', name: 'توب برجر', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 120, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 120 }], addons: crepeAddons },
  { id: 'ct10', name: 'سيراتشا', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 135, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 135 }], addons: crepeAddons },
  { id: 'ct11', name: 'ميكس مدخنات', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 125, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 125 }], addons: crepeAddons },
  { id: 'ct12', name: 'بيف ميجا', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 120, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 120 }], addons: crepeAddons },
  { id: 'ct13', name: 'لولي بوم', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 125, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 125 }], addons: crepeAddons },
  { id: 'ct14', name: 'تركي بيف', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 120, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 120 }], addons: crepeAddons },
  { id: 'ct15', name: 'تشيكن روكت', categorySlug: 'crepe-tuscanini', description: 'كريب توسكانيني', priceFrom: 130, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 130 }], addons: crepeAddons },
  {
    id: 'cs1',
    name: 'كريب نوتيلا',
    categorySlug: 'crepe-sweet',
    description: 'كريب حلو',
    priceFrom: 35,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 35 },
      { id: 'large', label: 'كبير', price: 55 },
    ],
  },
  {
    id: 'cs2',
    name: 'كريب وايت',
    categorySlug: 'crepe-sweet',
    description: 'كريب حلو',
    priceFrom: 40,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 40 },
      { id: 'large', label: 'كبير', price: 60 },
    ],
  },
  {
    id: 'cs3',
    name: 'كريب لوتس',
    categorySlug: 'crepe-sweet',
    description: 'كريب حلو',
    priceFrom: 45,
    availability: 'available',
    sizes: [
      { id: 'small', label: 'صغير', price: 45 },
      { id: 'large', label: 'كبير', price: 65 },
    ],
  },
  { id: 'pm1', name: 'برجر', categorySlug: 'pizza-meat', description: 'بيتزا لحوم', priceFrom: 120, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 120 }, { id: 'medium', label: 'وسط', price: 150 }, { id: 'large', label: 'كبير', price: 210 }, { id: 'family', label: 'فاميلي', price: 270 }] },
  { id: 'pm2', name: 'سوسيس', categorySlug: 'pizza-meat', description: 'بيتزا لحوم', priceFrom: 120, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 120 }, { id: 'medium', label: 'وسط', price: 150 }, { id: 'large', label: 'كبير', price: 210 }, { id: 'family', label: 'فاميلي', price: 270 }] },
  { id: 'pm3', name: 'مفروم', categorySlug: 'pizza-meat', description: 'بيتزا لحوم', priceFrom: 145, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 145 }, { id: 'medium', label: 'وسط', price: 185 }, { id: 'large', label: 'كبير', price: 250 }, { id: 'family', label: 'فاميلي', price: 310 }] },
  { id: 'pm4', name: 'شاورما لحم', categorySlug: 'pizza-meat', description: 'بيتزا لحوم', priceFrom: 145, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 145 }, { id: 'medium', label: 'وسط', price: 185 }, { id: 'large', label: 'كبير', price: 250 }, { id: 'family', label: 'فاميلي', price: 310 }] },
  { id: 'pm5', name: 'بيروني', categorySlug: 'pizza-meat', description: 'بيتزا لحوم', priceFrom: 140, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 140 }, { id: 'medium', label: 'وسط', price: 180 }, { id: 'large', label: 'كبير', price: 220 }, { id: 'family', label: 'فاميلي', price: 270 }] },
  { id: 'pm6', name: 'بسطرمة', categorySlug: 'pizza-meat', description: 'بيتزا لحوم', priceFrom: 170, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 170 }, { id: 'medium', label: 'وسط', price: 210 }, { id: 'large', label: 'كبير', price: 270 }, { id: 'family', label: 'فاميلي', price: 325 }] },
  { id: 'pm7', name: 'ميكس لحوم', categorySlug: 'pizza-meat', description: 'بيتزا لحوم', priceFrom: 135, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 135 }, { id: 'medium', label: 'وسط', price: 190 }, { id: 'large', label: 'كبير', price: 240 }, { id: 'family', label: 'فاميلي', price: 310 }] },
  { id: 'pc1', name: 'شاورما فراخ', categorySlug: 'pizza-chicken', description: 'بيتزا فراخ', priceFrom: 130, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 130 }, { id: 'medium', label: 'وسط', price: 180 }, { id: 'large', label: 'كبير', price: 230 }, { id: 'family', label: 'فاميلي', price: 310 }] },
  { id: 'pc2', name: 'زينجر', categorySlug: 'pizza-chicken', description: 'بيتزا فراخ', priceFrom: 140, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 140 }, { id: 'medium', label: 'وسط', price: 190 }, { id: 'large', label: 'كبير', price: 240 }, { id: 'family', label: 'فاميلي', price: 320 }] },
  { id: 'pc3', name: 'شيش', categorySlug: 'pizza-chicken', description: 'بيتزا فراخ', priceFrom: 130, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 130 }, { id: 'medium', label: 'وسط', price: 180 }, { id: 'large', label: 'كبير', price: 230 }, { id: 'family', label: 'فاميلي', price: 310 }] },
  { id: 'pc4', name: 'استربس', categorySlug: 'pizza-chicken', description: 'بيتزا فراخ', priceFrom: 130, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 130 }, { id: 'medium', label: 'وسط', price: 180 }, { id: 'large', label: 'كبير', price: 230 }, { id: 'family', label: 'فاميلي', price: 310 }] },
  { id: 'pc5', name: 'ميكس فراخ', categorySlug: 'pizza-chicken', description: 'بيتزا فراخ', priceFrom: 155, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 155 }, { id: 'medium', label: 'وسط', price: 195 }, { id: 'large', label: 'كبير', price: 250 }, { id: 'family', label: 'فاميلي', price: 315 }] },
  { id: 'px1', name: 'مارجريتا', categorySlug: 'pizza-mixed', description: 'بيتزا متنوع', priceFrom: 90, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 90 }, { id: 'medium', label: 'وسط', price: 115 }, { id: 'large', label: 'كبير', price: 150 }, { id: 'family', label: 'فاميلي', price: 190 }] },
  { id: 'px2', name: 'ميكس جبن', categorySlug: 'pizza-mixed', description: 'بيتزا متنوع', priceFrom: 120, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 120 }, { id: 'medium', label: 'وسط', price: 150 }, { id: 'large', label: 'كبير', price: 190 }, { id: 'family', label: 'فاميلي', price: 250 }] },
  { id: 'px3', name: 'تونة', categorySlug: 'pizza-mixed', description: 'بيتزا متنوع', priceFrom: 140, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 140 }, { id: 'medium', label: 'وسط', price: 195 }, { id: 'large', label: 'كبير', price: 240 }, { id: 'family', label: 'فاميلي', price: 305 }] },
  { id: 'px4', name: 'مشروم', categorySlug: 'pizza-mixed', description: 'بيتزا متنوع', priceFrom: 120, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 120 }, { id: 'medium', label: 'وسط', price: 150 }, { id: 'large', label: 'كبير', price: 180 }, { id: 'family', label: 'فاميلي', price: 230 }] },
  { id: 'pt1', name: 'تشيكن رانش', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 140, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 140 }, { id: 'medium', label: 'وسط', price: 190 }, { id: 'large', label: 'كبير', price: 240 }, { id: 'family', label: 'فاميلي', price: 320 }] },
  { id: 'pt2', name: 'تشيكن باربكيو', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 140, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 140 }, { id: 'medium', label: 'وسط', price: 190 }, { id: 'large', label: 'كبير', price: 240 }, { id: 'family', label: 'فاميلي', price: 320 }] },
  { id: 'pt3', name: 'الفريدو', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 140, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 140 }, { id: 'medium', label: 'وسط', price: 190 }, { id: 'large', label: 'كبير', price: 240 }, { id: 'family', label: 'فاميلي', price: 320 }] },
  { id: 'pt4', name: 'تشيكن فاير', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 155, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 155 }, { id: 'medium', label: 'وسط', price: 205 }, { id: 'large', label: 'كبير', price: 255 }, { id: 'family', label: 'فاميلي', price: 330 }] },
  { id: 'pt5', name: 'تشيكن تكساس', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 145, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 145 }, { id: 'medium', label: 'وسط', price: 195 }, { id: 'large', label: 'كبير', price: 260 }, { id: 'family', label: 'فاميلي', price: 335 }] },
  { id: 'pt6', name: 'الباستشيو', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 150, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 150 }, { id: 'medium', label: 'وسط', price: 210 }, { id: 'large', label: 'كبير', price: 270 }, { id: 'family', label: 'فاميلي', price: 350 }] },
  { id: 'pt7', name: 'دوز كباب', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 150, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 150 }, { id: 'medium', label: 'وسط', price: 190 }, { id: 'large', label: 'كبير', price: 260 }, { id: 'family', label: 'فاميلي', price: 335 }] },
  { id: 'pt8', name: 'سجق كيري', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 130, availability: 'available', sizes: [{ id: 'small', label: 'صغير', price: 130 }, { id: 'medium', label: 'وسط', price: 170 }, { id: 'large', label: 'كبير', price: 215 }, { id: 'family', label: 'فاميلي', price: 280 }] },
  { id: 'pt9', name: 'توسكانيني تشيكن', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 320, availability: 'available', sizes: [{ id: 'large', label: 'كبير', price: 320 }] },
  { id: 'pt10', name: 'توسكانيني بيف', categorySlug: 'pizza-tuscanini', description: 'بيتزا توسكانيني', priceFrom: 340, availability: 'available', sizes: [{ id: 'large', label: 'كبير', price: 340 }] },
  { id: 'pa1', name: 'نجرسكو', categorySlug: 'pasta', description: 'باستا', priceFrom: 110, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 110 }] },
  { id: 'pa2', name: 'جلاكسي', categorySlug: 'pasta', description: 'باستا', priceFrom: 115, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 115 }] },
  { id: 'pa3', name: 'استربس رانش', categorySlug: 'pasta', description: 'باستا', priceFrom: 120, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 120 }] },
  { id: 'pa4', name: 'زينجر شيدر', categorySlug: 'pasta', description: 'باستا', priceFrom: 125, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 125 }] },
  { id: 'pa5', name: 'بشاميل', categorySlug: 'pasta', description: 'باستا', priceFrom: 115, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 115 }] },
  { id: 'pa6', name: 'سجق', categorySlug: 'pasta', description: 'باستا', priceFrom: 90, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 90 }] },
  { id: 'pa7', name: 'عشاق جبن', categorySlug: 'pasta', description: 'باستا', priceFrom: 135, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 135 }] },
  { id: 'pa8', name: 'دوز كباب', categorySlug: 'pasta', description: 'باستا', priceFrom: 130, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 130 }] },
  { id: 'pa9', name: 'الفريدو', categorySlug: 'pasta', description: 'باستا', priceFrom: 110, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 110 }] },
  { id: 'pa10', name: 'سوسيس او برجر', categorySlug: 'pasta', description: 'باستا', priceFrom: 90, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 90 }] },
  { id: 'pa11', name: 'ميكس فراخ', categorySlug: 'pasta', description: 'باستا', priceFrom: 140, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 140 }] },
  { id: 'pa12', name: 'ميكس لحوم', categorySlug: 'pasta', description: 'باستا', priceFrom: 130, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 130 }] },
  { id: 'sf1', name: 'شاورما فراخ/شيش', categorySlug: 'sandwiches-french', description: 'ساندوتشات فرنساوي', priceFrom: 65, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 65 }] },
  { id: 'sf2', name: 'زينجر سوبريم', categorySlug: 'sandwiches-french', description: 'ساندوتشات فرنساوي', priceFrom: 85, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 85 }] },
  { id: 'sf3', name: 'سوسيس ميكسكانو', categorySlug: 'sandwiches-french', description: 'ساندوتشات فرنساوي', priceFrom: 55, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 55 }] },
  { id: 'sf4', name: 'شاورما لحم', categorySlug: 'sandwiches-french', description: 'ساندوتشات فرنساوي', priceFrom: 70, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 70 }] },
  { id: 'sf5', name: 'فاهيتا فراخ / لحم', categorySlug: 'sandwiches-french', description: 'ساندوتشات فرنساوي', priceFrom: 80, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 80 }] },
  { id: 'sf6', name: 'بوم فريت', categorySlug: 'sandwiches-french', description: 'ساندوتشات فرنساوي', priceFrom: 30, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 30 }] },
  { id: 'sk1', name: 'كايزر', categorySlug: 'sandwiches-kaiser', description: 'ساندوتشات كيزر', priceFrom: 65, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 65 }] },
  { id: 'sk2', name: 'تشيز برجر', categorySlug: 'sandwiches-kaiser', description: 'ساندوتشات كيزر', priceFrom: 85, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 85 }] },
  { id: 'sk3', name: 'توب برجر', categorySlug: 'sandwiches-kaiser', description: 'ساندوتشات كيزر', priceFrom: 100, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 100 }] },
  { id: 'sk4', name: 'سموكي زينجر', categorySlug: 'sandwiches-kaiser', description: 'ساندوتشات كيزر', priceFrom: 95, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 95 }] },
  { id: 'sk5', name: 'تشيكن فاير', categorySlug: 'sandwiches-kaiser', description: 'ساندوتشات كيزر', priceFrom: 115, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 115 }] },
  { id: 'sk6', name: 'توسكانيني', categorySlug: 'sandwiches-kaiser', description: 'ساندوتشات كيزر', priceFrom: 140, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 140 }] },
  { id: 'ap1', name: 'باكت بطاطس', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 25, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 25 }] },
  { id: 'ap2', name: 'باكت كرانشي', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
  { id: 'ap3', name: 'حلقات بصل', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 45, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 45 }] },
  { id: 'ap4', name: 'استيك موزاريلا', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 60, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 60 }] },
  { id: 'ap5', name: 'بطاطس شيدر / موزاريلا', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 45, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 45 }] },
  { id: 'ap6', name: 'كرسبي فرايز', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 75, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 75 }] },
  { id: 'ap7', name: 'كول سلو', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
  { id: 'ap8', name: 'بطاطس متبلة', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
  { id: 'ap9', name: 'تومية', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
  { id: 'ap10', name: 'مخلل', categorySlug: 'appetizers', description: 'مقبلات', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
  { id: 'dr1', name: 'مياه معدنية صغير', categorySlug: 'drinks', description: 'مشروبات', priceFrom: 10, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 10 }] },
  { id: 'dr2', name: 'مياه معدنية كبير', categorySlug: 'drinks', description: 'مشروبات', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
  { id: 'dr3', name: 'بيبسي', categorySlug: 'drinks', description: 'مشروبات', priceFrom: 25, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 25 }] },
  { id: 'dr4', name: 'سفن', categorySlug: 'drinks', description: 'مشروبات', priceFrom: 25, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 25 }] },
  { id: 'dr5', name: 'تويست', categorySlug: 'drinks', description: 'مشروبات', priceFrom: 25, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 25 }] },
  { id: 'dr6', name: 'فيروز', categorySlug: 'drinks', description: 'مشروبات', priceFrom: 25, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 25 }] },
  { id: 'wf1', name: 'وافل نوتيلا', categorySlug: 'waffle', description: 'وافل', priceFrom: 60, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 60 }] },
  { id: 'wf2', name: 'وافل وايت', categorySlug: 'waffle', description: 'وافل', priceFrom: 65, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 65 }] },
  { id: 'wf3', name: 'وافل لوتس', categorySlug: 'waffle', description: 'وافل', priceFrom: 70, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 70 }] },
  { id: 'ca1', name: 'موتزاريلا', categorySlug: 'crepe-addons', description: 'إضافات كريب', priceFrom: 20, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 20 }] },
  { id: 'ca2', name: 'رومي', categorySlug: 'crepe-addons', description: 'إضافات كريب', priceFrom: 20, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 20 }] },
  { id: 'ca3', name: 'شيدر', categorySlug: 'crepe-addons', description: 'إضافات كريب', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
  { id: 'ca4', name: 'كونو', categorySlug: 'crepe-addons', description: 'إضافات كريب', priceFrom: 25, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 25 }] },
  { id: 'ca5', name: 'رول', categorySlug: 'crepe-addons', description: 'إضافات كريب', priceFrom: 25, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 25 }] },
  { id: 'ca6', name: 'صوصات', categorySlug: 'crepe-addons', description: 'إضافات كريب', priceFrom: 15, availability: 'available', sizes: [{ id: 'single', label: 'سعر واحد', price: 15 }] },
];

export const mockOffers: Offer[] = [];
