import type { MenuCategory, MenuItem } from '@/types/menu';
import type { Offer } from '@/types/offers';

export const menuCategories: MenuCategory[] = [
  { id: 'c1', name: 'كريب', slug: 'crepe', description: 'كريب فراخ ولحوم وحشوات متنوعة.' },
  { id: 'c2', name: 'بيتزا', slug: 'pizza', description: 'بيتزا بصوص غني وإضافات شهية.' },
  { id: 'c3', name: 'باستا', slug: 'pasta', description: 'باستا بصوصات كريمي وأحمر.' },
  { id: 'c4', name: 'ساندوتشات', slug: 'sandwiches', description: 'ساندوتشات سريعة ومشبعة.' },
  { id: 'c5', name: 'مقبلات', slug: 'appetizers', description: 'بطاطس، أصابع، إضافات جانبية.' },
  { id: 'c6', name: 'مشروبات', slug: 'drinks', description: 'مشروبات غازية وعصائر باردة.' },
  { id: 'c7', name: 'عروض', slug: 'offers', description: 'تجميعات موفرة للأفراد والمجموعات.' },
];

export const featuredItems: MenuItem[] = [
  {
    id: 'm1',
    name: 'كريب تشيكن رانش',
    categorySlug: 'crepe',
    description: 'فراخ مشوية، صوص رانش، جبنة موزاريلا مع خيار مخلل.',
    priceFrom: 95,
    tags: ['الأكثر طلبًا'],
    availability: 'available',
    sizes: [
      { id: 's1', label: 'عادي', price: 95 },
      { id: 's2', label: 'دبل', price: 125 },
    ],
    addons: [
      { id: 'a1', label: 'جبنة إضافية', price: 15 },
      { id: 'a2', label: 'صوص رانش', price: 8 },
    ],
  },
  {
    id: 'm2',
    name: 'كريب سجق إيطالي حار',
    categorySlug: 'crepe',
    description: 'سجق إيطالي بصوص طماطم وتتبيلة حارة.',
    priceFrom: 88,
    tags: ['حار'],
    availability: 'limited',
    sizes: [
      { id: 's1', label: 'عادي', price: 88 },
      { id: 's2', label: 'كبير', price: 112 },
    ],
    addons: [
      { id: 'a1', label: 'هالبينو', price: 7 },
      { id: 'a2', label: 'جبنة شيدر', price: 12 },
    ],
  },
  {
    id: 'm3',
    name: 'بيتزا ميكس توسكانيني',
    categorySlug: 'pizza',
    description: 'تشكيلة فراخ ولحوم مع جبنة موزاريلا وصوص توسكانيني.',
    priceFrom: 165,
    tags: ['جديد'],
    availability: 'available',
    sizes: [
      { id: 's1', label: 'متوسط', price: 165 },
      { id: 's2', label: 'عائلي', price: 245 },
    ],
    addons: [
      { id: 'a1', label: 'جبنة إضافية', price: 20 },
      { id: 'a2', label: 'لحوم إضافية', price: 30 },
    ],
  },
  {
    id: 'm4',
    name: 'بيتزا بيبروني',
    categorySlug: 'pizza',
    description: 'شرائح بيبروني مدخنة مع صوص طماطم إيطالي.',
    priceFrom: 150,
    availability: 'available',
    sizes: [
      { id: 's1', label: 'متوسط', price: 150 },
      { id: 's2', label: 'كبير', price: 210 },
    ],
    addons: [
      { id: 'a1', label: 'زيتون أسود', price: 10 },
      { id: 'a2', label: 'جبنة بارميزان', price: 14 },
    ],
  },
  {
    id: 'm5',
    name: 'باستا ألفريدو دجاج',
    categorySlug: 'pasta',
    description: 'صوص كريمي غني مع قطع دجاج متبلة وفطر طازج.',
    priceFrom: 120,
    tags: ['الأكثر طلبًا'],
    availability: 'available',
    sizes: [
      { id: 's1', label: 'طبق عادي', price: 120 },
      { id: 's2', label: 'طبق كبير', price: 150 },
    ],
    addons: [
      { id: 'a1', label: 'خبز بالثوم', price: 18 },
      { id: 'a2', label: 'جبنة بارميزان', price: 15 },
    ],
  },
  {
    id: 'm6',
    name: 'باستا أرابياتا',
    categorySlug: 'pasta',
    description: 'باستا بصوص طماطم حار مع أعشاب إيطالية.',
    priceFrom: 110,
    tags: ['حار'],
    availability: 'available',
    sizes: [
      { id: 's1', label: 'طبق عادي', price: 110 },
      { id: 's2', label: 'طبق كبير', price: 142 },
    ],
    addons: [
      { id: 'a1', label: 'فلفل حار إضافي', price: 5 },
      { id: 'a2', label: 'دجاج مشوي', price: 25 },
    ],
  },
  {
    id: 'm7',
    name: 'ساندوتش فراخ كرسبي',
    categorySlug: 'sandwiches',
    description: 'فراخ كرسبي، خس، مايونيز حار، وخبز بريوش.',
    priceFrom: 78,
    tags: ['جديد'],
    availability: 'limited',
    sizes: [{ id: 's1', label: 'ساندوتش', price: 78 }],
    addons: [
      { id: 'a1', label: 'بطاطس جانبي', price: 25 },
      { id: 'a2', label: 'جبنة شيدر', price: 12 },
    ],
  },
  {
    id: 'm8',
    name: 'ساندوتش شيش طاووق',
    categorySlug: 'sandwiches',
    description: 'قطع شيش طاووق متبلة مع ثومية مميزة.',
    priceFrom: 82,
    availability: 'available',
    sizes: [{ id: 's1', label: 'ساندوتش', price: 82 }],
    addons: [
      { id: 'a1', label: 'مخلل إضافي', price: 4 },
      { id: 'a2', label: 'بطاطس جانبي', price: 25 },
    ],
  },
  {
    id: 'm9',
    name: 'بطاطس ويدجز',
    categorySlug: 'appetizers',
    description: 'بطاطس ويدجز متبلة تقدم مع صوص الجبنة.',
    priceFrom: 55,
    availability: 'available',
    sizes: [
      { id: 's1', label: 'صغير', price: 55 },
      { id: 's2', label: 'كبير', price: 75 },
    ],
    addons: [{ id: 'a1', label: 'صوص جبنة إضافي', price: 10 }],
  },
  {
    id: 'm10',
    name: 'موتزاريلا ستيكس',
    categorySlug: 'appetizers',
    description: 'أصابع جبنة مقرمشة تقدم ساخنة.',
    priceFrom: 68,
    tags: ['الأكثر طلبًا'],
    availability: 'available',
    sizes: [{ id: 's1', label: '6 قطع', price: 68 }],
    addons: [{ id: 'a1', label: 'صوص مارينارا', price: 8 }],
  },
  {
    id: 'm11',
    name: 'موهيتو ليمون نعناع',
    categorySlug: 'drinks',
    description: 'مشروب منعش بليمون طازج ونعناع.',
    priceFrom: 45,
    availability: 'available',
    sizes: [
      { id: 's1', label: 'وسط', price: 45 },
      { id: 's2', label: 'كبير', price: 58 },
    ],
  },
  {
    id: 'm12',
    name: 'كولا',
    categorySlug: 'drinks',
    description: 'مشروب غازي بارد.',
    priceFrom: 25,
    availability: 'unavailable',
    sizes: [{ id: 's1', label: 'كان', price: 25 }],
  },
  {
    id: 'm13',
    name: 'عرض الصاروخ',
    categorySlug: 'offers',
    description: 'كريب + بطاطس + مشروب بسعر موفر.',
    priceFrom: 139,
    tags: ['جديد'],
    availability: 'available',
    sizes: [{ id: 's1', label: 'عرض كامل', price: 139 }],
  },
  {
    id: 'm14',
    name: 'عرض العيلة',
    categorySlug: 'offers',
    description: 'بيتزا عائلية + باستا + 4 مشروبات.',
    priceFrom: 399,
    tags: ['الأكثر طلبًا'],
    availability: 'available',
    sizes: [{ id: 's1', label: 'عرض كامل', price: 399 }],
  },
];

export const mockOffers: Offer[] = [
  {
    id: 'o1',
    title: 'عرض الثنائي',
    description: '2 كريب + 2 مشروب بسعر مميز.',
    price: 210,
  },
  {
    id: 'o2',
    title: 'عرض العيلة',
    description: 'بيتزا عائلية + مقبلات + 4 مشروبات.',
    price: 399,
  },
];
